#define DEFAULT_CHANNEL_NAME "KvsChannel"
#define DEFAULT_ENABLE_SOUND true
#define DEFAULT_USE_TESTSRC false
#define DEFAULT_VIDEO_BITRATE 2048

#define ENV_VAR_DISPLAY ((PCHAR) "DISPLAY")

enum CMD_OPTIONS {
    CMD_OPT_DISPLAY_NAME = 1,
    CMD_OPT_DISABLE_SOUND,
    CMD_OPT_VIDEO_BITRATE,
    CMD_OPT_CHANNEL_NAME,
    CMD_OPT_USE_TESTSRC
};
